[package]
cairo-version = "=2.8.4"
name = "lutte"
version = "0.0.0"
# edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate --rpc-url https://free-rpc.nethermind.io/sepolia-juno/v0_7"


[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-rc.0" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]


[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-rc.0" }

[profile.dev.tool.dojo.env]
rpc_url = "https://free-rpc.nethermind.io/sepolia-juno/v0_7"
account_address = "0x049eE48eD0B2C31f22d1Aa8288dD3f65228F908d83AC63c3dCfbf8C5A3bf304c"
private_key = "0x05ca7a3739ec424c4d10ada7d6715c4815bda09100bef0aca3f5d7fd093fca73"