[package]
cairo-version = "=2.9.2"
name = "lutte"
version = "0.0.0"
# edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate --mainnet --fee strk && sozo inspect"


[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.1.2" }



[tool.dojo]
initializer_class_hash = "0xbeef"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]


[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.1.2" }

[profile.mainnet]


[tool.voyager]
lutte = { path = "lib.cairo" }